FROM ubuntu

LABEL maintainer="Alexander Lachmann <alexander.lachmann@mssm.edu>"

# Python installs
RUN apt-get update && apt-get install -y \
    python3 \
    python3-dev \
    python3-pip \
    python3-setuptools

# pip installs
RUN pip3 install --upgrade pip
RUN pip3 install flask
RUN pip3 install flask-cors
RUN pip3 install Flask-Session
RUN pip3 install requests
RUN pip3 install python-dateutil --upgrade
RUN pip3 install pandas
RUN pip3 install numpy==1.20.0
RUN pip3 install qnorm

WORKDIR /usr/local/src

RUN mkdir -p /app/data
COPY . /app

EXPOSE 5000

WORKDIR /app

RUN chmod -R 777 /app
ENTRYPOINT ./entrypoint.sh